version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kesterriley/mdb-test-10-4-server
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: make build
      - run:
          name: Scan Image
          command: make scan
      - run:
          name: Publish Docker Image to Docker Hub
          command: make publish
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
